-- ══════════════════════════════════════════════════════════════
-- BANK QUESTIONS SEED (computer-science) — GENERATED FILE, DO NOT EDIT BY HAND
-- Part 22 of 22. Built by tools/build_question_bank.py.
-- Run every part, in order, AFTER supabase/bank-questions-schema.sql.
-- Each part is a standalone statement — paste just this one file into
-- the Supabase SQL editor and click Run, then move to the next part.
-- Safe to re-run (upserts by question_key).
-- Generated: 2026-07-24T18:45:57Z
-- ══════════════════════════════════════════════════════════════
insert into bank_questions (question_key, subject_slug, page_id, page_name, source, qtype, marks, snapshot, answer_key)
values
('computer-science:2-5-2-the-integrated-development-environment-ide:tips:56ae7cb2', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'tips', 'mcq', 1, '{"readingTitle": "tip — Naming the IDE tool, not just describing it", "reading": "<p>Many marks are lost by describing what a tool does without naming it, or vice versa. If a question asks to <strong>identify</strong> a tool, give the <strong>name</strong> (e.g. \"a breakpoint\"). If it asks to <strong>explain</strong> or <strong>describe</strong>, give the name <strong>and</strong> say what it does.</p>\n<ul>\n<li>Learn the tools in pairs — name + what it does: syntax highlighting → colours the code; breakpoint → pauses the program; watching variables → shows a variable''s value.</li>\n</ul>", "question": "A question asks you to ''identify'' the IDE tool that pauses a program at a chosen line.", "options": ["Describe in detail how the whole of the IDE works, from start to finish", "Name the tool: a breakpoint", "List every debugging tool the IDE provides, one after another", "Explain why syntax errors are different from logic errors"]}'::jsonb, '{"answer": 1, "explain": "''Identify'' asks for the name of the tool — a breakpoint. A full description is only needed if the question says ''explain'' or ''describe''."}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:tips:ef25fb73', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'tips', 'mcq', 1, '{"readingTitle": "explain — Editing tools vs debugging tools — know which is which", "reading": "<p>Questions often ask you to sort IDE facilities into groups. Keep two groups clear in your head:</p>\n<ul>\n<li><strong>Helps you write code</strong>: syntax highlighting, auto-indentation, auto-complete.</li>\n<li><strong>Helps you find and fix errors</strong>: syntax error flagging, breakpoints, stepping, watching variables.</li>\n</ul>\n<p>The run-time environment and the translator sit slightly apart — they let the code be <strong>tested</strong> and <strong>run</strong> from inside the IDE.</p>", "question": "Which of these belongs in the group ''helps a programmer find and fix errors''?", "options": ["Auto-complete, because it inserts a suggested name for the programmer automatically", "Watching variables", "Auto-indentation, because it lines new code up to match the block it is inside", "Syntax highlighting, because it colours the code to make it easier to read"]}'::jsonb, '{"answer": 1, "explain": "Watching variables is a debugging tool used to find errors. Auto-complete, auto-indentation and syntax highlighting all help with writing code."}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:tips:e0d2983b', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'tips', 'mcq', 1, '{"readingTitle": "tip — Explain HOW a tool helps, not just WHAT it is", "reading": "<p>A common exam pattern is: \"State a tool an IDE provides, and explain how it helps a programmer.\" Two marks usually need <strong>two separate ideas</strong> — naming the tool is not enough on its own for full marks.</p>\n<ul>\n<li><strong>Weak:</strong> \"Breakpoints\" (name only).</li>\n<li><strong>Better:</strong> \"A breakpoint pauses the program at a chosen line, so the programmer can examine what is happening at that point rather than guessing.\"</li>\n</ul>", "question": "A question is worth 2 marks and asks you to ''state a debugging tool and explain how it helps''. What should your answer include?", "options": ["Just the name of the tool, written as clearly and neatly as possible", "The name of the tool AND an explanation of how it helps the programmer", "A full list of every debugging tool the IDE provides, without any explanation", "A diagram of the IDE''s editor window, with no written explanation at all"]}'::jsonb, '{"answer": 1, "explain": "A 2-mark ''state and explain'' question needs both the name of the tool and an explanation of how it helps — not just one or the other."}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:fib:79f11954', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'fib', 'fib', 1, '{"question": "The _____ is the part of the IDE where the programmer types the code.", "blankOptions": {"B1": ["translator", "syntax highlighting", "editor", "auto-indentation"]}}'::jsonb, '{"blanks": {"B1": "editor"}}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:fib:4101f64f', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'fib', 'fib', 1, '{"question": "The IDE facility that colours keywords and strings to show the code''s structure is called _____.", "blankOptions": {"B1": ["editor", "syntax", "auto-complete", "syntax highlighting"]}}'::jsonb, '{"blanks": {"B1": "syntax highlighting"}}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:fib:4571dcb9', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'fib', 'fib', 1, '{"question": "The feature that automatically indents a new line to match its block is called _____.", "blankOptions": {"B1": ["auto-indentation", "syntax", "syntax highlighting", "translator"]}}'::jsonb, '{"blanks": {"B1": "auto-indentation"}}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:fib:0fc1e248', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'fib', 'fib', 1, '{"question": "The feature that suggests variable and function names as you type is called _____.", "blankOptions": {"B1": ["auto-complete", "editor", "syntax highlighting", "syntax"]}}'::jsonb, '{"blanks": {"B1": "auto-complete"}}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:fib:42113582', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'fib', 'fib', 1, '{"question": "A mistake that breaks the grammar rules of a programming language is called a _____ error.", "blankOptions": {"B1": ["editor", "syntax", "translator", "auto-indentation"]}}'::jsonb, '{"blanks": {"B1": "syntax"}}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:fib:70225da7', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'fib', 'fib', 1, '{"question": "A _____ pauses a running program at a chosen line so its variables can be examined.", "blankOptions": {"B1": ["auto-complete", "syntax", "translator", "breakpoint"]}}'::jsonb, '{"blanks": {"B1": "breakpoint"}}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:fib:7db20c79', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'fib', 'fib', 1, '{"question": "The IDE''s built-in compiler or interpreter that translates and runs code is called the _____.", "blankOptions": {"B1": ["editor", "syntax highlighting", "syntax", "translator"]}}'::jsonb, '{"blanks": {"B1": "translator"}}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:eb3935e9', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Editor”?", "options": ["A mistake where the program runs but produces the wrong result", "Where the programmer types the code", "Suggests variable, function and keyword names as the programmer types", "Runs the program one line at a time from a chosen point"]}'::jsonb, '{"answer": 1, "explain": "“Editor” means: Where the programmer types the code"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:05b167a0', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Syntax highlighting”?", "options": ["Colours keywords, strings and other parts of the code to show its structure", "A built-in compiler or interpreter that translates and runs the code", "A mistake where the program runs but produces the wrong result", "Pauses the program at a chosen line so it can be examined"]}'::jsonb, '{"answer": 0, "explain": "“Syntax highlighting” means: Colours keywords, strings and other parts of the code to show its structure"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:6e27c3ae', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Auto-indentation”?", "options": ["Pauses the program at a chosen line so it can be examined", "Where the programmer types the code", "Automatically indents a new line to match the block it is inside", "A mistake where the program runs but produces the wrong result"]}'::jsonb, '{"answer": 2, "explain": "“Auto-indentation” means: Automatically indents a new line to match the block it is inside"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:3ceabe77', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Auto-complete”?", "options": ["Pauses the program at a chosen line so it can be examined", "A built-in compiler or interpreter that translates and runs the code", "Software that brings the tools to write, test and debug a program together in one place", "Suggests variable, function and keyword names as the programmer types"]}'::jsonb, '{"answer": 3, "explain": "“Auto-complete” means: Suggests variable, function and keyword names as the programmer types"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:c715ccb2', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Syntax error”?", "options": ["A mistake that breaks the grammar rules of the programming language", "A mistake where the program runs but produces the wrong result", "Where the programmer types the code", "Suggests variable, function and keyword names as the programmer types"]}'::jsonb, '{"answer": 0, "explain": "“Syntax error” means: A mistake that breaks the grammar rules of the programming language"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:7b64fbd9', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Logic error”?", "options": ["Automatically indents a new line to match the block it is inside", "A mistake where the program runs but produces the wrong result", "A built-in compiler or interpreter that translates and runs the code", "Software that brings the tools to write, test and debug a program together in one place"]}'::jsonb, '{"answer": 1, "explain": "“Logic error” means: A mistake where the program runs but produces the wrong result"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:d1a1f3d3', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Breakpoint”?", "options": ["Pauses the program at a chosen line so it can be examined", "Automatically indents a new line to match the block it is inside", "Software that brings the tools to write, test and debug a program together in one place", "Where the programmer types the code"]}'::jsonb, '{"answer": 0, "explain": "“Breakpoint” means: Pauses the program at a chosen line so it can be examined"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:c9da5f92', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Stepping”?", "options": ["Runs the program one line at a time from a chosen point", "Shows the current value of chosen variables as the program runs", "A built-in compiler or interpreter that translates and runs the code", "Automatically indents a new line to match the block it is inside"]}'::jsonb, '{"answer": 0, "explain": "“Stepping” means: Runs the program one line at a time from a chosen point"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:3eab4dff', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Watching variables”?", "options": ["Lets the programmer run and test the program from inside the IDE", "Shows the current value of chosen variables as the program runs", "A mistake where the program runs but produces the wrong result", "A mistake that breaks the grammar rules of the programming language"]}'::jsonb, '{"answer": 1, "explain": "“Watching variables” means: Shows the current value of chosen variables as the program runs"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:c7a18318', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Run-time environment”?", "options": ["A mistake that breaks the grammar rules of the programming language", "Lets the programmer run and test the program from inside the IDE", "Automatically indents a new line to match the block it is inside", "Pauses the program at a chosen line so it can be examined"]}'::jsonb, '{"answer": 1, "explain": "“Run-time environment” means: Lets the programmer run and test the program from inside the IDE"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:f33936c1', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Translator”?", "options": ["A mistake where the program runs but produces the wrong result", "Pauses the program at a chosen line so it can be examined", "A built-in compiler or interpreter that translates and runs the code", "Suggests variable, function and keyword names as the programmer types"]}'::jsonb, '{"answer": 2, "explain": "“Translator” means: A built-in compiler or interpreter that translates and runs the code"}'::jsonb),
('computer-science:2-5-2-the-integrated-development-environment-ide:match:4e0552cb', 'computer-science', 'computer-science:2-5-2-the-integrated-development-environment-ide', '2.5.2 The Integrated Development Environment (IDE)', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “IDE”?", "options": ["A mistake that breaks the grammar rules of the programming language", "Where the programmer types the code", "A built-in compiler or interpreter that translates and runs the code", "Software that brings the tools to write, test and debug a program together in one place"]}'::jsonb, '{"answer": 3, "explain": "“IDE” means: Software that brings the tools to write, test and debug a program together in one place"}'::jsonb)
on conflict (question_key) do update set
  subject_slug = excluded.subject_slug,
  page_id = excluded.page_id, page_name = excluded.page_name,
  source = excluded.source, qtype = excluded.qtype, marks = excluded.marks,
  snapshot = excluded.snapshot, answer_key = excluded.answer_key,
  updated_at = now();
