-- ══════════════════════════════════════════════════════════════
-- BANK QUESTIONS SEED (spanish) — GENERATED FILE, DO NOT EDIT BY HAND
-- Part 7 of 7. Built by tools/build_question_bank.py.
-- Run every part, in order, AFTER supabase/bank-questions-schema.sql.
-- Each part is a standalone statement — paste just this one file into
-- the Supabase SQL editor and click Run, then move to the next part.
-- Safe to re-run (upserts by question_key).
-- Generated: 2026-07-18T16:24:22Z
-- ══════════════════════════════════════════════════════════════
insert into bank_questions (question_key, subject_slug, page_id, page_name, source, qtype, marks, snapshot, answer_key)
values
('spanish:2-2-exercise-health-problems-and-advice:match:409c0857', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “hacer ejercicio”?", "options": ["my head hurts", "to be fit", "to do exercise", "throat"]}'::jsonb, '{"answer": 2, "explain": "“hacer ejercicio” means: to do exercise"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:1cdc83ad', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “estar en forma”?", "options": ["to be fit", "to do exercise", "to go to bed", "to be tired"]}'::jsonb, '{"answer": 0, "explain": "“estar en forma” means: to be fit"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:a3f8f2db', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “me duele la cabeza”?", "options": ["throat", "to be tired", "to do exercise", "my head hurts"]}'::jsonb, '{"answer": 3, "explain": "“me duele la cabeza” means: my head hurts"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:88186bf4', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “me duelen los pies”?", "options": ["to go to bed", "my head hurts", "one should rest", "my feet hurt"]}'::jsonb, '{"answer": 3, "explain": "“me duelen los pies” means: my feet hurt"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:5a671b9d', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “la garganta”?", "options": ["to be fit", "bad for your health", "throat", "to relax"]}'::jsonb, '{"answer": 2, "explain": "“la garganta” means: throat"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:50570df3', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “estar cansado”?", "options": ["to be tired", "my head hurts", "to stop smoking", "to be fit"]}'::jsonb, '{"answer": 0, "explain": "“estar cansado” means: to be tired"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:9df7b988', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “el estrés”?", "options": ["my head hurts", "stress", "to do exercise", "bad for your health"]}'::jsonb, '{"answer": 1, "explain": "“el estrés” means: stress"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:87953604', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “dejar de fumar”?", "options": ["throat", "to be tired", "one should rest", "to stop smoking"]}'::jsonb, '{"answer": 3, "explain": "“dejar de fumar” means: to stop smoking"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:f3df8924', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “se debe descansar”?", "options": ["my feet hurt", "my head hurts", "one should rest", "to relax"]}'::jsonb, '{"answer": 2, "explain": "“se debe descansar” means: one should rest"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:d5315945', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “acostarse”?", "options": ["my head hurts", "to do exercise", "my feet hurt", "to go to bed"]}'::jsonb, '{"answer": 3, "explain": "“acostarse” means: to go to bed"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:899809b1', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “relajarse”?", "options": ["to do exercise", "stress", "to relax", "to stop smoking"]}'::jsonb, '{"answer": 2, "explain": "“relajarse” means: to relax"}'::jsonb),
('spanish:2-2-exercise-health-problems-and-advice:match:b36ab8ff', 'spanish', 'spanish:2-2-exercise-health-problems-and-advice', '2.2 Exercise, Health Problems and Advice', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “malo para la salud”?", "options": ["bad for your health", "my feet hurt", "to be fit", "my head hurts"]}'::jsonb, '{"answer": 0, "explain": "“malo para la salud” means: bad for your health"}'::jsonb)
on conflict (question_key) do update set
  subject_slug = excluded.subject_slug,
  page_id = excluded.page_id, page_name = excluded.page_name,
  source = excluded.source, qtype = excluded.qtype, marks = excluded.marks,
  snapshot = excluded.snapshot, answer_key = excluded.answer_key,
  updated_at = now();
