-- ══════════════════════════════════════════════════════════════
-- BANK QUESTIONS SEED (additional-maths) — GENERATED FILE, DO NOT EDIT BY HAND
-- Part 5 of 5. Built by tools/build_question_bank.py.
-- Run every part, in order, AFTER supabase/bank-questions-schema.sql.
-- Each part is a standalone statement — paste just this one file into
-- the Supabase SQL editor and click Run, then move to the next part.
-- Safe to re-run (upserts by question_key).
-- Generated: 2026-07-17T20:50:45Z
-- ══════════════════════════════════════════════════════════════
insert into bank_questions (question_key, subject_slug, page_id, page_name, source, qtype, marks, snapshot, answer_key)
values
('additional-maths:2-4-sequences-and-recurrence-relationships:learn:1c905a15', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'learn', 'mcq', 1, '{"readingTitle": "How is recurrence used to model money and populations?", "reading": "<p>Recurrence relationships model any quantity that changes by the <strong>same factor</strong> each period — the classic case is <strong>compound interest</strong>.</p>\n            <ul>\n              <li><strong>Growth of \\( r\\% \\) per period</strong> → multiply by \\( \\left(1 + \\frac{r}{100}\\right) \\). So \\( 3\\% \\) interest gives \\( x_{n+1} = 1.03\\,x_n \\).</li>\n              <li><strong>Depreciation / decay of \\( r\\% \\)</strong> → multiply by \\( \\left(1 - \\frac{r}{100}\\right) \\). So losing \\( 15\\% \\) a year gives \\( x_{n+1} = 0.85\\,x_n \\).</li>\n              <li><strong>Regular top-up savings</strong> combine both: e.g. \\( x_{n+1} = 1.03\\,x_n + 50 \\) grows the balance by \\( 3\\% \\) and then adds a \\( £50 \\) deposit.</li>\n            </ul>\n            <p><strong>Worked example — £500 invested at \\( 3\\% \\) per year, \\( x_1 = 500 \\), \\( x_{n+1} = 1.03\\,x_n \\):</strong></p>\n            <table class=\"worked\">\n              <tr><td>1. \\( x_1 = 500 \\) (the amount invested).</td></tr>\n              <tr><td>2. After 1 year: \\( x_2 = 1.03 \\times 500 = 515 \\).</td></tr>\n              <tr><td>3. After 2 years: \\( x_3 = 1.03 \\times 515 = 530.45 \\).</td></tr>\n              <tr><td>4. After 3 years: \\( x_4 = 1.03 \\times 530.45 = 546.36 \\) (to the nearest penny).</td></tr>\n            </table>\n            <p>Interest is earned on the interest, so the balance grows a little faster each year.</p>", "question": "A car worth \\( £8000 \\) depreciates by \\( 20\\% \\) each year. Which recurrence models its value?", "options": ["\\( x_{n+1} = 0.8x_n \\)", "\\( x_{n+1} = 1.2x_n \\)", "\\( x_{n+1} = x_n - 20 \\)", "\\( x_{n+1} = 0.2x_n \\)"]}'::jsonb, '{"answer": 0, "explain": "Losing \\( 20\\% \\) leaves \\( 80\\% \\), so multiply by \\( 1 - 0.20 = 0.8 \\)."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:misc:85d9672e', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'misc', 'mcq', 1, '{"readingTitle": "Misconception check", "reading": "<p><strong>❌ Common misconception:</strong> For \\( x_{n+1} = 5x_n \\) with \\( x_1 = 2 \\), writing \\( x_2 = 2 + 5 = 7 \\).</p><p><strong>✅ The correct idea:</strong> The rule multiplies, it does not add. A weak answer treats \\( 5x_n \\) as \\( x_n + 5 \\); a strong answer writes \\( x_2 = 5 \\times 2 = 10 \\).</p>", "question": "For \\( x_{n+1} = 5x_n \\) with \\( x_1 = 2 \\), what is \\( x_2 \\)?", "options": ["\\( 10 \\)", "\\( 7 \\)", "\\( 25 \\)", "\\( 5 \\)"]}'::jsonb, '{"answer": 0, "explain": "\\( x_2 = 5 \\times 2 = 10 \\)."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:misc:e97fabf3', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'misc', 'mcq', 1, '{"readingTitle": "Misconception check", "reading": "<p><strong>❌ Common misconception:</strong> Trying to generate \\( x_{n+2} = x_{n+1} + x_n \\) from a single starting value.</p><p><strong>✅ The correct idea:</strong> A second-order rule needs two terms to start. A weak answer stalls with only \\( x_1 \\); a strong answer uses both \\( x_1 \\) and \\( x_2 \\), then builds \\( x_3 = x_2 + x_1 \\).</p>", "question": "How many starting values does \\( x_{n+2} = x_{n+1} + x_n \\) need?", "options": ["Two", "One", "None", "Three"]}'::jsonb, '{"answer": 0, "explain": "It reaches back two terms, so it needs the first two terms."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:misc:d59cdd12', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'misc', 'mcq', 1, '{"readingTitle": "Misconception check", "reading": "<p><strong>❌ Common misconception:</strong> Doing the whole iteration on the calculator and writing down only the final answer.</p><p><strong>✅ The correct idea:</strong> Examiners award a mark for each correct term, so unshown working can lose marks after a slip. A weak answer shows nothing; a strong answer sets each line out formally: \\( x_3 = \\dots,\\ x_4 = \\dots,\\ x_5 = \\dots \\). This also guards against a transcription error when copying from the calculator.</p>", "question": "Why set out each term on its own line?", "options": ["Each correct term earns its own mark and it prevents copying slips", "It uses more paper", "It is required by law", "To make the answer look longer"]}'::jsonb, '{"answer": 0, "explain": "Every term is worth a mark, and formal working avoids calculator transcription errors."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:misc:b0a14992', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'misc', 'mcq', 1, '{"readingTitle": "Misconception check", "reading": "<p><strong>❌ Common misconception:</strong> Not recognising the phrase ''recurrence relationship'' and leaving the question blank.</p><p><strong>✅ The correct idea:</strong> ''Recurrence relationship'' just means a term-to-term rule — a way of getting the next term from earlier ones. A weak answer gives up on the wording; a strong answer reads the rule and simply substitutes the given values.</p>", "question": "What does ''recurrence relationship'' mean?", "options": ["A rule giving each term from earlier terms", "The sum of all the terms", "The 100th term of the sequence", "A type of graph"]}'::jsonb, '{"answer": 0, "explain": "It is a term-to-term rule — nothing more exotic than substituting into the given formula."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:misc:c8c267c3', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'misc', 'mcq', 1, '{"readingTitle": "Misconception check", "reading": "<p><strong>❌ Common misconception:</strong> Modelling 3% compound interest with the multiplier \\( 0.03 \\) or \\( 1.3 \\).</p><p><strong>✅ The correct idea:</strong> A percentage increase adds to 1, and 3% is \\( 0.03 \\), not \\( 0.3 \\). A weak answer uses \\( 0.03 \\) or \\( 1.3 \\); a strong answer uses \\( 1 + 0.03 = 1.03 \\).</p>", "question": "The multiplier for a 3% yearly increase is:", "options": ["\\( 1.03 \\)", "\\( 0.03 \\)", "\\( 1.3 \\)", "\\( 3 \\)"]}'::jsonb, '{"answer": 0, "explain": "\\( 1 + \\frac{3}{100} = 1.03 \\)."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:tips:c498a55d', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'tips', 'mcq', 1, '{"readingTitle": "tip — Show every term (method marks)", "reading": "<p>On a \"[3]\" recurrence question, each correct term earns <strong>its own mark</strong>. For \\( x_{n+2} = x_{n+1} + 2x_n \\), write \\( x_3 \\), \\( x_4 \\) and \\( x_5 \\) on separate lines — a slip then costs one mark, not all three. Doing it all silently on the calculator risks losing the lot to one arithmetic error.</p>", "question": "Why write each term of a recurrence on its own line?", "options": ["Each correct term earns a separate mark", "It is not necessary", "To slow yourself down", "To fill the answer space"]}'::jsonb, '{"answer": 0, "explain": "Marks are awarded term by term, so visible correct terms protect your score."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:tips:ab6b6cd3', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'tips', 'mcq', 1, '{"readingTitle": "explain — ''Determine'' means value plus working", "reading": "<p>The command word <strong>\"Determine\"</strong> asks for the value <em>supported by working</em> — you must show how you reached it, not just state the final number. For \\( x_5 \\), show the terms you built on the way (\\( x_3 \\), \\( x_4 \\)) so the method is clear.</p>", "question": "What does ''Determine the value of \\( x_5 \\)'' require?", "options": ["The value with working shown", "Only the final number", "A graph of the sequence", "A decimal approximation"]}'::jsonb, '{"answer": 0, "explain": "''Determine'' expects justification — the value backed by visible working."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:tips:ee706019', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'tips', 'mcq', 1, '{"readingTitle": "tip — Turn a percentage into a multiplier", "reading": "<p>For modelling questions, convert the rate to a multiplier: a rise of \\( r\\% \\) gives \\( \\left(1 + \\frac{r}{100}\\right) \\); a fall of \\( r\\% \\) gives \\( \\left(1 - \\frac{r}{100}\\right) \\). So \\( 3\\% \\) growth is \\( 1.03 \\) and \\( 15\\% \\) depreciation is \\( 0.85 \\). Then the model is simply \\( x_{n+1} = (\\text{multiplier})\\,x_n \\).</p>", "question": "The multiplier for a 7% yearly decrease is:", "options": ["\\( 0.93 \\)", "\\( 1.07 \\)", "\\( 0.07 \\)", "\\( 0.7 \\)"]}'::jsonb, '{"answer": 0, "explain": "A fall of 7% leaves 93%, so multiply by \\( 1 - 0.07 = 0.93 \\)."}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:fib:a78b1ff7', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'fib', 'fib', 1, '{"question": "A rule that gives each term of a sequence from earlier terms is called a ___B1___ relationship.", "blankOptions": {"B1": ["0.15", "recurrence", "geometric", "multiplied"]}}'::jsonb, '{"blanks": {"B1": "recurrence"}}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:fib:07bf26ff', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'fib', 'fib', 1, '{"question": "As well as the rule, you need a ___B1___ value before you can generate the sequence.", "blankOptions": {"B1": ["starting", "two", "11", "0.85"]}}'::jsonb, '{"blanks": {"B1": "starting"}}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:fib:8d21a455', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'fib', 'fib', 1, '{"question": "In \\( x_{n+1} = x_n + a \\) the fixed number \\( a \\) is ___B1___ to each term, giving an arithmetic sequence.", "blankOptions": {"B1": ["0.15", "subtracted", "multiplied", "added"]}}'::jsonb, '{"blanks": {"B1": "added"}}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:fib:2cc02a0f', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'fib', 'fib', 1, '{"question": "In \\( x_{n+1} = a x_n \\) each term is ___B1___ by \\( a \\), giving a geometric sequence.", "blankOptions": {"B1": ["geometric", "multiplied", "two", "recurrence"]}}'::jsonb, '{"blanks": {"B1": "multiplied"}}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:fib:645af2d9', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'fib', 'fib', 1, '{"question": "A second-order rule such as \\( x_{n+2} = x_{n+1} + x_n \\) needs ___B1___ starting values.", "blankOptions": {"B1": ["recurrence", "11", "divided", "two"]}}'::jsonb, '{"blanks": {"B1": "two"}}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:fib:673036f8', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'fib', 'fib', 1, '{"question": "Compound interest of 3% per year gives \\( x_{n+1} = k x_n \\) where the multiplier \\( k \\) is ___B1___.", "blankOptions": {"B1": ["starting", "two", "7", "1.03"]}}'::jsonb, '{"blanks": {"B1": "1.03"}}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:fib:c146cfd8', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'fib', 'fib', 1, '{"question": "An asset that loses 15% of its value each year has multiplier ___B1___.", "blankOptions": {"B1": ["7", "0.85", "added", "1.03"]}}'::jsonb, '{"blanks": {"B1": "0.85"}}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:fib:c5f8bfb5', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'fib', 'fib', 2, '{"question": "For \\( x_{n+1} = x_n + 4 \\) with \\( x_1 = 3 \\), the second term is ___B1___ and the third term is ___B2___.", "blankOptions": {"B1": ["multiplied", "1.03", "7", "one"], "B2": ["0.15", "added", "11", "two"]}}'::jsonb, '{"blanks": {"B1": "7", "B2": "11"}}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:c9f8805c', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( x_{n+1} = x_n + 4 \\)”?", "options": ["Arithmetic: adds 4 to each term", "\\( x_{n+1} = 2x_n,\\ x_1 = 3 \\)", "Geometric: multiplies each term by 3", "3% compound interest each year"]}'::jsonb, '{"answer": 0, "explain": "“\\( x_{n+1} = x_n + 4 \\)” means: Arithmetic: adds 4 to each term"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:a5cdefc8', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( x_{n+1} = 3x_n \\)”?", "options": ["The first term, needed to begin the sequence", "Arithmetic: adds 4 to each term", "\\( x_{n+1} = x_n + 3,\\ x_1 = 2 \\)", "Geometric: multiplies each term by 3"]}'::jsonb, '{"answer": 3, "explain": "“\\( x_{n+1} = 3x_n \\)” means: Geometric: multiplies each term by 3"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:3995ab1d', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( x_{n+2} = x_{n+1} + x_n \\)”?", "options": ["3% compound interest each year", "The \\( n\\)th term of the sequence", "\\( x_{n+1} = x_n + 3,\\ x_1 = 2 \\)", "Each term is the sum of the two before it"]}'::jsonb, '{"answer": 3, "explain": "“\\( x_{n+2} = x_{n+1} + x_n \\)” means: Each term is the sum of the two before it"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:fce5518c', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( x_{n+1} = 1.03x_n \\)”?", "options": ["Depreciation of 15% each year", "Arithmetic: adds 4 to each term", "The first term, needed to begin the sequence", "3% compound interest each year"]}'::jsonb, '{"answer": 3, "explain": "“\\( x_{n+1} = 1.03x_n \\)” means: 3% compound interest each year"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:3ac37921', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( x_{n+1} = 0.85x_n \\)”?", "options": ["The first term, needed to begin the sequence", "Arithmetic: adds 4 to each term", "Each term is the sum of the two before it", "Depreciation of 15% each year"]}'::jsonb, '{"answer": 3, "explain": "“\\( x_{n+1} = 0.85x_n \\)” means: Depreciation of 15% each year"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:528240bf', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( x_{n+1} = 1.02x_n \\)”?", "options": ["The first term, needed to begin the sequence", "The term immediately after \\( x_n \\)", "Population growing 2% each year", "The \\( n\\)th term of the sequence"]}'::jsonb, '{"answer": 2, "explain": "“\\( x_{n+1} = 1.02x_n \\)” means: Population growing 2% each year"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:5845325a', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( 2,\\ 5,\\ 8,\\ 11,\\ \\dots \\)”?", "options": ["\\( x_{n+1} = 2x_n,\\ x_1 = 3 \\)", "\\( x_{n+1} = x_n + 3,\\ x_1 = 2 \\)", "Arithmetic: adds 4 to each term", "The term immediately after \\( x_n \\)"]}'::jsonb, '{"answer": 1, "explain": "“\\( 2,\\ 5,\\ 8,\\ 11,\\ \\dots \\)” means: \\( x_{n+1} = x_n + 3,\\ x_1 = 2 \\)"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:443498e0', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( 3,\\ 6,\\ 12,\\ 24,\\ \\dots \\)”?", "options": ["The \\( n\\)th term of the sequence", "\\( x_{n+2} = x_{n+1} + x_n \\) (Fibonacci)", "Arithmetic: adds 4 to each term", "\\( x_{n+1} = 2x_n,\\ x_1 = 3 \\)"]}'::jsonb, '{"answer": 3, "explain": "“\\( 3,\\ 6,\\ 12,\\ 24,\\ \\dots \\)” means: \\( x_{n+1} = 2x_n,\\ x_1 = 3 \\)"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:9cc2b354', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( 1,\\ 1,\\ 2,\\ 3,\\ 5,\\ \\dots \\)”?", "options": ["Depreciation of 15% each year", "The first term, needed to begin the sequence", "Arithmetic: adds 4 to each term", "\\( x_{n+2} = x_{n+1} + x_n \\) (Fibonacci)"]}'::jsonb, '{"answer": 3, "explain": "“\\( 1,\\ 1,\\ 2,\\ 3,\\ 5,\\ \\dots \\)” means: \\( x_{n+2} = x_{n+1} + x_n \\) (Fibonacci)"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:0771f1e2', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( x_n \\)”?", "options": ["Geometric: multiplies each term by 3", "3% compound interest each year", "The \\( n\\)th term of the sequence", "Arithmetic: adds 4 to each term"]}'::jsonb, '{"answer": 2, "explain": "“\\( x_n \\)” means: The \\( n\\)th term of the sequence"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:dfc61448', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “\\( x_{n+1} \\)”?", "options": ["The term immediately after \\( x_n \\)", "\\( x_{n+1} = x_n + 3,\\ x_1 = 2 \\)", "\\( x_{n+1} = 2x_n,\\ x_1 = 3 \\)", "The \\( n\\)th term of the sequence"]}'::jsonb, '{"answer": 0, "explain": "“\\( x_{n+1} \\)” means: The term immediately after \\( x_n \\)"}'::jsonb),
('additional-maths:2-4-sequences-and-recurrence-relationships:match:37510a76', 'additional-maths', 'additional-maths:2-4-sequences-and-recurrence-relationships', '2.4 Sequences and Recurrence Relationships', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Starting value”?", "options": ["3% compound interest each year", "The first term, needed to begin the sequence", "Geometric: multiplies each term by 3", "\\( x_{n+1} = x_n + 3,\\ x_1 = 2 \\)"]}'::jsonb, '{"answer": 1, "explain": "“Starting value” means: The first term, needed to begin the sequence"}'::jsonb)
on conflict (question_key) do update set
  subject_slug = excluded.subject_slug,
  page_id = excluded.page_id, page_name = excluded.page_name,
  source = excluded.source, qtype = excluded.qtype, marks = excluded.marks,
  snapshot = excluded.snapshot, answer_key = excluded.answer_key,
  updated_at = now();
