-- ══════════════════════════════════════════════════════════════
-- BANK QUESTIONS SEED (additional-maths) — GENERATED FILE, DO NOT EDIT BY HAND
-- Part 21 of 21. Built by tools/build_question_bank.py.
-- Run every part, in order, AFTER supabase/bank-questions-schema.sql.
-- Each part is a standalone statement — paste just this one file into
-- the Supabase SQL editor and click Run, then move to the next part.
-- Safe to re-run (upserts by question_key).
-- Generated: 2026-07-18T09:11:09Z
-- ══════════════════════════════════════════════════════════════
insert into bank_questions (question_key, subject_slug, page_id, page_name, source, qtype, marks, snapshot, answer_key)
values
('additional-maths:11-2-synoptic-and-unstructured-problems:fib:580b88af', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'fib', 'fib', 1, '{"question": "A problem-solving question given with little or no scaffolding is described as ___B1___.", "blankOptions": {"B1": ["exact", "half", "lower", "unstructured"]}}'::jsonb, '{"blanks": {"B1": "unstructured"}}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:fib:77fd2ee1', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'fib', 'fib', 1, '{"question": "The command word ___B1___ instructs you to use the result of the previous part rather than start again.", "blankOptions": {"B1": ["synoptic", "hence", "upper", "1.2"]}}'::jsonb, '{"blanks": {"B1": "hence"}}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:fib:5424470d', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'fib', 'fib', 2, '{"question": "To find the area between two curves you integrate the ___B1___ curve minus the lower curve, between their points of ___B2___.", "blankOptions": {"B1": ["upper", "lower", "double", "1.2"], "B2": ["intersection", "substitute", "gradient", "unstructured"]}}'::jsonb, '{"blanks": {"B1": "upper", "B2": "intersection"}}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:fib:acf09cb2', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'fib', 'fib', 2, '{"question": "The derivative \\( \\frac{dy}{dx} \\) gives the ___B1___ function; to get the gradient of a tangent you must ___B2___ the point''s x-value.", "blankOptions": {"B1": ["lower", "follow-through", "gradient", "double"], "B2": ["substitute", "follow-through", "hence", "upper"]}}'::jsonb, '{"blanks": {"B1": "gradient", "B2": "substitute"}}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:fib:8cb8e7b0', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'fib', 'fib', 1, '{"question": "A mark awarded for a correct method applied to a wrong earlier answer is called a ___B1___ mark.", "blankOptions": {"B1": ["upper", "tangent", "follow-through", "synoptic"]}}'::jsonb, '{"blanks": {"B1": "follow-through"}}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:fib:c143ab1f', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'fib', 'fib', 1, '{"question": "Because 100 marks are worth 120 minutes, you should budget roughly ___B1___ minutes per mark.", "blankOptions": {"B1": ["exact", "lower", "tangent", "1.2"]}}'::jsonb, '{"blanks": {"B1": "1.2"}}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:fib:37508953', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'fib', 'fib', 2, '{"question": "When a figure is symmetric about the y-axis you can find one ___B1___ of the area and then ___B2___ it.", "blankOptions": {"B1": ["synoptic", "exact", "half", "tangent"], "B2": ["gradient", "substitute", "double", "upper"]}}'::jsonb, '{"blanks": {"B1": "half", "B2": "double"}}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:73bb5ca0', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Curve + tangent + trapped area”?", "options": ["Use the result of the previous part", "About 15 minutes (≈1.2 min per mark)", "Coordinate geometry, differentiation and integration", "Integrate (upper − lower) between intersections"]}'::jsonb, '{"answer": 2, "explain": "“Curve + tangent + trapped area” means: Coordinate geometry, differentiation and integration"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:5971034e', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Line is a tangent to a circle”?", "options": ["About 15 minutes (≈1.2 min per mark)", "Full method shown; calculator-only scores 0", "Leave as a surd or fraction, not a decimal", "Substitute, then discriminant = 0"]}'::jsonb, '{"answer": 3, "explain": "“Line is a tangent to a circle” means: Substitute, then discriminant = 0"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:95fbc6dc', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “''A root is \\( x = 2 \\)''”?", "options": ["It must be positive", "Set \\( \\text{f}(2) = 0 \\)", "Coordinate geometry, differentiation and integration", "About 15 minutes (≈1.2 min per mark)"]}'::jsonb, '{"answer": 1, "explain": "“''A root is \\( x = 2 \\)''” means: Set \\( \\text{f}(2) = 0 \\)"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:0c7d10dd', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Area between two curves”?", "options": ["Substitute, then discriminant = 0", "Correct method on a wrong earlier answer still scores", "Integrate (upper − lower) between intersections", "About 15 minutes (≈1.2 min per mark)"]}'::jsonb, '{"answer": 2, "explain": "“Area between two curves” means: Integrate (upper − lower) between intersections"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:72201fce', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Symmetric figure about the \\( y \\)-axis”?", "options": ["Correct method on a wrong earlier answer still scores", "Work one half, then double", "Set \\( \\text{f}(2) = 0 \\)", "Integrate (upper − lower) between intersections"]}'::jsonb, '{"answer": 1, "explain": "“Symmetric figure about the \\( y \\)-axis” means: Work one half, then double"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:1e0d66d2', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “''Hence'' at the start of a part”?", "options": ["Use the result of the previous part", "It must be positive", "Full method shown; calculator-only scores 0", "Leave as a surd or fraction, not a decimal"]}'::jsonb, '{"answer": 0, "explain": "“''Hence'' at the start of a part” means: Use the result of the previous part"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:f48fbf4d', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “''In this question you must show detailed reasoning''”?", "options": ["Use the result of the previous part", "Give an ordered pair \\( (x,\\ y) \\)", "Work one half, then double", "Full method shown; calculator-only scores 0"]}'::jsonb, '{"answer": 3, "explain": "“''In this question you must show detailed reasoning''” means: Full method shown; calculator-only scores 0"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:b19850b1', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “''Exact'' answer required”?", "options": ["Correct method on a wrong earlier answer still scores", "Full method shown; calculator-only scores 0", "Solve \\( \\frac{dy}{dx} = 0 \\)", "Leave as a surd or fraction, not a decimal"]}'::jsonb, '{"answer": 3, "explain": "“''Exact'' answer required” means: Leave as a surd or fraction, not a decimal"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:a404b2bb', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “''Find the coordinates of D''”?", "options": ["Coordinate geometry, differentiation and integration", "Give an ordered pair \\( (x,\\ y) \\)", "Work one half, then double", "About 15 minutes (≈1.2 min per mark)"]}'::jsonb, '{"answer": 1, "explain": "“''Find the coordinates of D''” means: Give an ordered pair \\( (x,\\ y) \\)"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:5ba5cfc5', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Turning point of a curve”?", "options": ["Solve \\( \\frac{dy}{dx} = 0 \\)", "Give an ordered pair \\( (x,\\ y) \\)", "Full method shown; calculator-only scores 0", "Set \\( \\text{f}(2) = 0 \\)"]}'::jsonb, '{"answer": 0, "explain": "“Turning point of a curve” means: Solve \\( \\frac{dy}{dx} = 0 \\)"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:6d266aec', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Nature of a stationary point”?", "options": ["Leave as a surd or fraction, not a decimal", "Full method shown; calculator-only scores 0", "Solve \\( \\frac{dy}{dx} = 0 \\)", "Sign of \\( \\frac{d^2y}{dx^2} \\) (or gradient either side)"]}'::jsonb, '{"answer": 3, "explain": "“Nature of a stationary point” means: Sign of \\( \\frac{d^2y}{dx^2} \\) (or gradient either side)"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:c55a651b', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Time budget on a 13-mark question”?", "options": ["Leave as a surd or fraction, not a decimal", "It must be positive", "Integrate (upper − lower) between intersections", "About 15 minutes (≈1.2 min per mark)"]}'::jsonb, '{"answer": 3, "explain": "“Time budget on a 13-mark question” means: About 15 minutes (≈1.2 min per mark)"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:f6278e99', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Follow-through (ft) mark”?", "options": ["Solve \\( \\frac{dy}{dx} = 0 \\)", "It must be positive", "Set \\( \\text{f}(2) = 0 \\)", "Correct method on a wrong earlier answer still scores"]}'::jsonb, '{"answer": 3, "explain": "“Follow-through (ft) mark” means: Correct method on a wrong earlier answer still scores"}'::jsonb),
('additional-maths:11-2-synoptic-and-unstructured-problems:match:ddff2b94', 'additional-maths', 'additional-maths:11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Sanity check on an area”?", "options": ["Use the result of the previous part", "Set \\( \\text{f}(2) = 0 \\)", "It must be positive", "Leave as a surd or fraction, not a decimal"]}'::jsonb, '{"answer": 2, "explain": "“Sanity check on an area” means: It must be positive"}'::jsonb)
on conflict (question_key) do update set
  subject_slug = excluded.subject_slug,
  page_id = excluded.page_id, page_name = excluded.page_name,
  source = excluded.source, qtype = excluded.qtype, marks = excluded.marks,
  snapshot = excluded.snapshot, answer_key = excluded.answer_key,
  updated_at = now();
