-- ══════════════════════════════════════════════════════════════
-- BANK QUESTIONS SEED (business) — GENERATED FILE, DO NOT EDIT BY HAND
-- Part 27 of 27. Built by tools/build_question_bank.py.
-- Run every part, in order, AFTER supabase/bank-questions-schema.sql.
-- Each part is a standalone statement — paste just this one file into
-- the Supabase SQL editor and click Run, then move to the next part.
-- Safe to re-run (upserts by question_key).
-- Generated: 2026-07-16T17:18:43Z
-- ══════════════════════════════════════════════════════════════
insert into bank_questions (question_key, subject_slug, page_id, page_name, source, qtype, marks, snapshot, answer_key)
values
('business:7-1-final:match:cfc40d3c', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Interdependent Nature of Business”?", "options": ["Data including revenues, costs, profit, rates of return, break-even and cash flow, used to help a business make decisions.", "The possibility the business will lose money from decisions it makes; owners may lose invested capital.", "The links between different areas of business that affect decision making, risks, rewards and the use of financial information.", "The profit made by a business as a return for the risk taken by its owners or shareholders."]}'::jsonb, '{"answer": 2, "explain": "“Interdependent Nature of Business” means: The links between different areas of business that affect decision making, risks, rewards and the use of financial information."}'::jsonb),
('business:7-1-final:match:204b5779', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Financial Information”?", "options": ["Data including revenues, costs, profit, rates of return, break-even and cash flow, used to help a business make decisions.", "The possibility the business will lose money from decisions it makes; owners may lose invested capital.", "The profit made by a business as a return for the risk taken by its owners or shareholders.", "Benefits to owners such as independence, satisfaction, personal achievement and having an impact on consumers."]}'::jsonb, '{"answer": 0, "explain": "“Financial Information” means: Data including revenues, costs, profit, rates of return, break-even and cash flow, used to help a business make decisions."}'::jsonb),
('business:7-1-final:match:518315b7', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Financial Risk”?", "options": ["The profit made by a business as a return for the risk taken by its owners or shareholders.", "Benefits to owners such as independence, satisfaction, personal achievement and having an impact on consumers.", "Personal costs to the business owner including health problems, stress, and strained family relationships.", "The possibility the business will lose money from decisions it makes; owners may lose invested capital."]}'::jsonb, '{"answer": 3, "explain": "“Financial Risk” means: The possibility the business will lose money from decisions it makes; owners may lose invested capital."}'::jsonb),
('business:7-1-final:match:48fac65c', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Financial Reward”?", "options": ["Benefits to owners such as independence, satisfaction, personal achievement and having an impact on consumers.", "Personal costs to the business owner including health problems, stress, and strained family relationships.", "A measure of how well a business is doing, with key measures being sales, profits and rates of return.", "The profit made by a business as a return for the risk taken by its owners or shareholders."]}'::jsonb, '{"answer": 3, "explain": "“Financial Reward” means: The profit made by a business as a return for the risk taken by its owners or shareholders."}'::jsonb),
('business:7-1-final:match:42630de9', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Non-Financial Reward”?", "options": ["Personal costs to the business owner including health problems, stress, and strained family relationships.", "A measure of how well a business is doing, with key measures being sales, profits and rates of return.", "Linking knowledge from Component 01 and Component 02 to show how different areas of business are connected.", "Benefits to owners such as independence, satisfaction, personal achievement and having an impact on consumers."]}'::jsonb, '{"answer": 3, "explain": "“Non-Financial Reward” means: Benefits to owners such as independence, satisfaction, personal achievement and having an impact on consumers."}'::jsonb),
('business:7-1-final:match:b03ae5cf', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Non-Financial Risk”?", "options": ["A measure of how well a business is doing, with key measures being sales, profits and rates of return.", "Linking knowledge from Component 01 and Component 02 to show how different areas of business are connected.", "The process of interaction and integration between people, companies and governments worldwide.", "Personal costs to the business owner including health problems, stress, and strained family relationships."]}'::jsonb, '{"answer": 3, "explain": "“Non-Financial Risk” means: Personal costs to the business owner including health problems, stress, and strained family relationships."}'::jsonb),
('business:7-1-final:match:0e41e6d6', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Business Performance”?", "options": ["Linking knowledge from Component 01 and Component 02 to show how different areas of business are connected.", "The process of interaction and integration between people, companies and governments worldwide.", "A financial measure used to compare the profitability of different investment options; however, it does not account for inflation.", "A measure of how well a business is doing, with key measures being sales, profits and rates of return."]}'::jsonb, '{"answer": 3, "explain": "“Business Performance” means: A measure of how well a business is doing, with key measures being sales, profits and rates of return."}'::jsonb),
('business:7-1-final:match:fa59b8b3', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Synopticity”?", "options": ["Linking knowledge from Component 01 and Component 02 to show how different areas of business are connected.", "The process of interaction and integration between people, companies and governments worldwide.", "A financial measure used to compare the profitability of different investment options; however, it does not account for inflation.", "The movement of money into and out of a business over a period of time — a business can be profitable but still fail if cash runs out."]}'::jsonb, '{"answer": 0, "explain": "“Synopticity” means: Linking knowledge from Component 01 and Component 02 to show how different areas of business are connected."}'::jsonb),
('business:7-1-final:match:896f6651', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Globalisation”?", "options": ["A financial measure used to compare the profitability of different investment options; however, it does not account for inflation.", "The process of interaction and integration between people, companies and governments worldwide.", "The movement of money into and out of a business over a period of time — a business can be profitable but still fail if cash runs out.", "The level of sales at which total revenue equals total costs — the business makes neither a profit nor a loss."]}'::jsonb, '{"answer": 1, "explain": "“Globalisation” means: The process of interaction and integration between people, companies and governments worldwide."}'::jsonb),
('business:7-1-final:match:3301d56c', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Average Rate of Return (ARR)”?", "options": ["The movement of money into and out of a business over a period of time — a business can be profitable but still fail if cash runs out.", "The level of sales at which total revenue equals total costs — the business makes neither a profit nor a loss.", "The links between different areas of business that affect decision making, risks, rewards and the use of financial information.", "A financial measure used to compare the profitability of different investment options; however, it does not account for inflation."]}'::jsonb, '{"answer": 3, "explain": "“Average Rate of Return (ARR)” means: A financial measure used to compare the profitability of different investment options; however, it does not account for inflation."}'::jsonb),
('business:7-1-final:match:ef6661b1', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Cash Flow”?", "options": ["The movement of money into and out of a business over a period of time — a business can be profitable but still fail if cash runs out.", "The level of sales at which total revenue equals total costs — the business makes neither a profit nor a loss.", "The links between different areas of business that affect decision making, risks, rewards and the use of financial information.", "Data including revenues, costs, profit, rates of return, break-even and cash flow, used to help a business make decisions."]}'::jsonb, '{"answer": 0, "explain": "“Cash Flow” means: The movement of money into and out of a business over a period of time — a business can be profitable but still fail if cash runs out."}'::jsonb),
('business:7-1-final:match:39cd68b5', 'business', 'business:7-1-final', '7.1 Interdependent Nature of Business', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Break-Even”?", "options": ["The links between different areas of business that affect decision making, risks, rewards and the use of financial information.", "The level of sales at which total revenue equals total costs — the business makes neither a profit nor a loss.", "Data including revenues, costs, profit, rates of return, break-even and cash flow, used to help a business make decisions.", "The possibility the business will lose money from decisions it makes; owners may lose invested capital."]}'::jsonb, '{"answer": 1, "explain": "“Break-Even” means: The level of sales at which total revenue equals total costs — the business makes neither a profit nor a loss."}'::jsonb)
on conflict (question_key) do update set
  subject_slug = excluded.subject_slug,
  page_id = excluded.page_id, page_name = excluded.page_name,
  source = excluded.source, qtype = excluded.qtype, marks = excluded.marks,
  snapshot = excluded.snapshot, answer_key = excluded.answer_key,
  updated_at = now();
