-- ══════════════════════════════════════════════════════════════
-- BANK QUESTIONS SEED (economics) — GENERATED FILE, DO NOT EDIT BY HAND
-- Part 13 of 13. Built by tools/build_question_bank.py.
-- Run every part, in order, AFTER supabase/bank-questions-schema.sql.
-- Each part is a standalone statement — paste just this one file into
-- the Supabase SQL editor and click Run, then move to the next part.
-- Safe to re-run (upserts by question_key).
-- Generated: 2026-07-16T17:18:42Z
-- ══════════════════════════════════════════════════════════════
insert into bank_questions (question_key, subject_slug, page_id, page_name, source, qtype, marks, snapshot, answer_key)
values
('economics:3-8-limitations-of-markets:fib:d5e8c920', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'fib', 'fib', 2, '{"question": "The ___B1___ problem means people can benefit from a good without ___B2___ for it, so firms cannot profit from supplying it.", "blankOptions": {"B1": ["another", "third", "free-rider", "left"], "B2": ["left", "third", "right", "paying"]}}'::jsonb, '{"blanks": {"B1": "free-rider", "B2": "paying"}}'::jsonb),
('economics:3-8-limitations-of-markets:fib:85fb0685', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'fib', 'fib', 2, '{"question": "Opportunity cost is the next best ___B1___ given up when the government spends money on one policy instead of ___B2___.", "blankOptions": {"B1": ["demand", "paying", "alternative", "social"], "B2": ["another", "free-rider", "left", "right"]}}'::jsonb, '{"blanks": {"B1": "alternative", "B2": "another"}}'::jsonb),
('economics:3-8-limitations-of-markets:match:d78e6cb4', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Externality”?", "options": ["A cost to a third party not reflected in the market price", "A benefit to a third party not reflected in the market price", "A cost or benefit of an economic activity that falls on a third party", "The cost paid directly by the producer or consumer"]}'::jsonb, '{"answer": 2, "explain": "“Externality” means: A cost or benefit of an economic activity that falls on a third party"}'::jsonb),
('economics:3-8-limitations-of-markets:match:0769117c', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Negative externality”?", "options": ["A benefit to a third party not reflected in the market price", "A cost to a third party not reflected in the market price", "The cost paid directly by the producer or consumer", "Private cost plus the external cost imposed on third parties"]}'::jsonb, '{"answer": 1, "explain": "“Negative externality” means: A cost to a third party not reflected in the market price"}'::jsonb),
('economics:3-8-limitations-of-markets:match:9b2df420', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Positive externality”?", "options": ["The cost paid directly by the producer or consumer", "A benefit to a third party not reflected in the market price", "Private cost plus the external cost imposed on third parties", "The benefit received directly by the producer or consumer"]}'::jsonb, '{"answer": 1, "explain": "“Positive externality” means: A benefit to a third party not reflected in the market price"}'::jsonb),
('economics:3-8-limitations-of-markets:match:13efdc52', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Private cost”?", "options": ["Private cost plus the external cost imposed on third parties", "The cost paid directly by the producer or consumer", "The benefit received directly by the producer or consumer", "Private benefit plus the external benefit enjoyed by third parties"]}'::jsonb, '{"answer": 1, "explain": "“Private cost” means: The cost paid directly by the producer or consumer"}'::jsonb),
('economics:3-8-limitations-of-markets:match:7b094fa3', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Social cost”?", "options": ["The benefit received directly by the producer or consumer", "Private cost plus the external cost imposed on third parties", "Private benefit plus the external benefit enjoyed by third parties", "Benefiting from a good or service without paying for it"]}'::jsonb, '{"answer": 1, "explain": "“Social cost” means: Private cost plus the external cost imposed on third parties"}'::jsonb),
('economics:3-8-limitations-of-markets:match:a498dae3', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Private benefit”?", "options": ["Private benefit plus the external benefit enjoyed by third parties", "The benefit received directly by the producer or consumer", "Benefiting from a good or service without paying for it", "A tax on a good or service that raises a firm''s costs and shifts supply left"]}'::jsonb, '{"answer": 1, "explain": "“Private benefit” means: The benefit received directly by the producer or consumer"}'::jsonb),
('economics:3-8-limitations-of-markets:match:325e7caa', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Social benefit”?", "options": ["Benefiting from a good or service without paying for it", "Private benefit plus the external benefit enjoyed by third parties", "A tax on a good or service that raises a firm''s costs and shifts supply left", "Money paid to a producer to lower costs and increase supply"]}'::jsonb, '{"answer": 1, "explain": "“Social benefit” means: Private benefit plus the external benefit enjoyed by third parties"}'::jsonb),
('economics:3-8-limitations-of-markets:match:8d75beba', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Free-rider problem”?", "options": ["A tax on a good or service that raises a firm''s costs and shifts supply left", "Money paid to a producer to lower costs and increase supply", "Government directly supplying a good or service, e.g. the NHS", "Benefiting from a good or service without paying for it"]}'::jsonb, '{"answer": 3, "explain": "“Free-rider problem” means: Benefiting from a good or service without paying for it"}'::jsonb),
('economics:3-8-limitations-of-markets:match:8f7a7de8', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Indirect tax”?", "options": ["A tax on a good or service that raises a firm''s costs and shifts supply left", "Money paid to a producer to lower costs and increase supply", "Government directly supplying a good or service, e.g. the NHS", "Laws that ban or restrict a harmful activity directly"]}'::jsonb, '{"answer": 0, "explain": "“Indirect tax” means: A tax on a good or service that raises a firm''s costs and shifts supply left"}'::jsonb),
('economics:3-8-limitations-of-markets:match:776d176c', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Subsidy”?", "options": ["Money paid to a producer to lower costs and increase supply", "Government directly supplying a good or service, e.g. the NHS", "Laws that ban or restrict a harmful activity directly", "Government campaigns to encourage or discourage consumption of a good"]}'::jsonb, '{"answer": 0, "explain": "“Subsidy” means: Money paid to a producer to lower costs and increase supply"}'::jsonb),
('economics:3-8-limitations-of-markets:match:fa3928ed', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “State provision”?", "options": ["Laws that ban or restrict a harmful activity directly", "Government campaigns to encourage or discourage consumption of a good", "A cost or benefit of an economic activity that falls on a third party", "Government directly supplying a good or service, e.g. the NHS"]}'::jsonb, '{"answer": 3, "explain": "“State provision” means: Government directly supplying a good or service, e.g. the NHS"}'::jsonb),
('economics:3-8-limitations-of-markets:match:e3240f44', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Legislation / regulation”?", "options": ["Government campaigns to encourage or discourage consumption of a good", "Laws that ban or restrict a harmful activity directly", "A cost or benefit of an economic activity that falls on a third party", "A cost to a third party not reflected in the market price"]}'::jsonb, '{"answer": 1, "explain": "“Legislation / regulation” means: Laws that ban or restrict a harmful activity directly"}'::jsonb),
('economics:3-8-limitations-of-markets:match:b26fb381', 'economics', 'economics:3-8-limitations-of-markets', '3.8 Limitations of Markets', 'match', 'mcq', 1, '{"question": "Which definition matches the key term “Information provision”?", "options": ["Government campaigns to encourage or discourage consumption of a good", "A cost or benefit of an economic activity that falls on a third party", "A cost to a third party not reflected in the market price", "A benefit to a third party not reflected in the market price"]}'::jsonb, '{"answer": 0, "explain": "“Information provision” means: Government campaigns to encourage or discourage consumption of a good"}'::jsonb)
on conflict (question_key) do update set
  subject_slug = excluded.subject_slug,
  page_id = excluded.page_id, page_name = excluded.page_name,
  source = excluded.source, qtype = excluded.qtype, marks = excluded.marks,
  snapshot = excluded.snapshot, answer_key = excluded.answer_key,
  updated_at = now();
