-- ══════════════════════════════════════════════════════════════
-- PLATFORM TOPIC MASTER SEED (additional-maths) — GENERATED FILE, DO NOT EDIT BY HAND
-- Part 2 of 2. Built by tools/build_question_bank.py.
-- Run every part, in order, AFTER supabase/subjects-v2-s5-master-content.sql.
-- Seeds the master `sections` that 'Make a copy' pre-fills a fork with.
-- Safe to re-run (upserts by (subject_slug, topic_slug)).
-- Generated: 2026-07-18T04:46:50Z
-- ══════════════════════════════════════════════════════════════
insert into platform_topic_master (subject_slug, topic_slug, page_name, sections)
values
('additional-maths', '7-3-solving-exponential-equations', '7.3 Solving Exponential Equations', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>7.3 Solving Exponential Equations</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '7-4-reduction-to-linear-form', '7.4 Reduction to Linear Form', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>7.4 Reduction to Linear Form</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '8-1-the-gradient-function', '8.1 The Gradient Function', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>8.1 The Gradient Function</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '8-2-tangents-and-normals', '8.2 Tangents and Normals', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>8.2 Tangents and Normals</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '8-3-stationary-points-and-curve-sketching', '8.3 Stationary Points and Curve Sketching', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>8.3 Stationary Points and Curve Sketching</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '9-1-indefinite-integration', '9.1 Indefinite Integration', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>9.1 Indefinite Integration</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '9-2-definite-integrals-and-areas', '9.2 Definite Integrals and Areas', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>9.2 Definite Integrals and Areas</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '9-3-numerical-areas-and-the-trapezium-rule', '9.3 Numerical Areas and the Trapezium Rule', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>9.3 Numerical Areas and the Trapezium Rule</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '10-1-kinematics', '10.1 Kinematics', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>10.1 Kinematics</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '10-2-solving-equations-numerically', '10.2 Solving Equations Numerically', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>10.2 Solving Equations Numerically</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '11-1-command-words-and-detailed-reasoning', '11.1 Command Words and Detailed Reasoning', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>11.1 Command Words and Detailed Reasoning</strong> will appear here soon.</p>"}]}}'::jsonb),
('additional-maths', '11-2-synoptic-and-unstructured-problems', '11.2 Synoptic and Unstructured Problems', '{"learn": {"enabled": true, "items": [{"title": "This topic is being written", "html": "<p>🚧 <strong>Content for this topic is on its way.</strong> Key Learning notes, practice questions and exam-style questions for <strong>11.2 Synoptic and Unstructured Problems</strong> will appear here soon.</p>"}]}}'::jsonb)
on conflict (subject_slug, topic_slug) do update set
  page_name = excluded.page_name,
  sections = excluded.sections,
  updated_at = now();
